"""Unit tests for the clinical review engine.

Validates settings, data models, ICD-10 lookup, confidence routing,
and tool dispatch — all without requiring an ANTHROPIC_API_KEY.
"""

from pathlib import Path

import pytest


@pytest.mark.unit
class TestApplicationSettings:
    """Tests for application_settings.py."""

    def test_settings_loads_defaults(self) -> None:
        """Settings should provide default values for all non-secret fields."""
        from prior_auth_demo.application_settings import ApplicationSettings

        settings = ApplicationSettings(
            anthropic_api_key="test-key-not-real",  # noqa: S106
            _env_file=None,
        )
        assert settings.claude_model_id == "claude-sonnet-4-6"
        assert settings.auto_approve_confidence_threshold == 0.85
        assert settings.human_review_confidence_threshold == 0.60
        assert settings.log_level == "INFO"

    def test_settings_requires_api_key(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """Settings should raise ValidationError when ANTHROPIC_API_KEY is missing."""
        from pydantic import ValidationError

        from prior_auth_demo.application_settings import ApplicationSettings

        monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
        with pytest.raises(ValidationError):
            ApplicationSettings(_env_file=None)


def _make_claim_response():  # noqa: ANN202
    """Helper to build a minimal valid FHIR ClaimResponse for tests."""
    from fhir.resources.R4B.claimresponse import ClaimResponse

    return ClaimResponse(
        status="active",
        type={
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/claim-type",
                    "code": "professional",
                }
            ]
        },
        use="preauthorization",
        patient={"reference": "Patient/test-123"},
        insurer={"reference": "Organization/test-insurer"},
        outcome="complete",
        created="2026-03-24",
    )


@pytest.mark.unit
class TestClinicalReviewResultModel:
    """Tests for ClinicalReviewResult Pydantic model validation."""

    def test_model_validates_with_all_fields(self) -> None:
        """ClinicalReviewResult accepts all valid fields."""
        from prior_auth_demo.clinical_review_engine import ClinicalReviewResult

        result = ClinicalReviewResult(
            determination="APPROVED",
            confidence_score=0.92,
            clinical_rationale="Meets medical necessity criteria.",
            guideline_citations=["CMS LCD L12345"],
            missing_documentation=None,
            fhir_claim_response=_make_claim_response(),
            review_duration_seconds=12.5,
        )
        assert result.determination == "APPROVED"
        assert result.confidence_score == 0.92

    def test_model_rejects_invalid_determination(self) -> None:
        """ClinicalReviewResult rejects invalid determination values."""
        from pydantic import ValidationError

        from prior_auth_demo.clinical_review_engine import ClinicalReviewResult

        with pytest.raises(ValidationError):
            ClinicalReviewResult(
                determination="MAYBE",  # type: ignore[arg-type]
                confidence_score=0.5,
                clinical_rationale="test",
                guideline_citations=[],
                missing_documentation=None,
                fhir_claim_response=_make_claim_response(),
                review_duration_seconds=1.0,
            )

    def test_model_rejects_confidence_out_of_range(self) -> None:
        """ClinicalReviewResult rejects confidence scores outside 0.0-1.0."""
        from pydantic import ValidationError

        from prior_auth_demo.clinical_review_engine import ClinicalReviewResult

        with pytest.raises(ValidationError):
            ClinicalReviewResult(
                determination="APPROVED",
                confidence_score=1.5,
                clinical_rationale="test",
                guideline_citations=[],
                missing_documentation=None,
                fhir_claim_response=_make_claim_response(),
                review_duration_seconds=1.0,
            )

    def test_model_with_polyfactory(self) -> None:
        """ClinicalReviewResult can be generated by polyfactory."""
        from polyfactory.factories.pydantic_factory import ModelFactory

        from prior_auth_demo.clinical_review_engine import ClinicalReviewResult

        class ClinicalReviewResultFactory(ModelFactory):
            __model__ = ClinicalReviewResult
            fhir_claim_response = _make_claim_response()

        instance = ClinicalReviewResultFactory.build()
        assert instance.determination in (
            "APPROVED",
            "DENIED",
            "PENDED_FOR_REVIEW",
            "PENDED_MISSING_INFO",
        )
        assert 0.0 <= instance.confidence_score <= 1.0


@pytest.mark.unit
class TestIcd10Lookup:
    """Tests for ICD-10 code lookup from local reference data."""

    def test_lookup_returns_correct_description(self, reference_data_dir: Path) -> None:
        """Known ICD-10 code M54.5 should return 'Low back pain'."""
        from prior_auth_demo.clinical_review_engine import lookup_icd10_code

        result = lookup_icd10_code("M54.5", reference_data_dir / "icd10cm_codes_2026.tsv")
        assert result is not None
        assert result["code"] == "M54.5"
        assert "low back pain" in result["description"].lower()

    def test_lookup_returns_none_for_invalid_code(self, reference_data_dir: Path) -> None:
        """Invalid ICD-10 code should return None."""
        from prior_auth_demo.clinical_review_engine import lookup_icd10_code

        result = lookup_icd10_code("ZZ99.99", reference_data_dir / "icd10cm_codes_2026.tsv")
        assert result is None

    def test_lookup_finds_oncology_code(self, reference_data_dir: Path) -> None:
        """C34.11 (lung cancer) should be found in reference data."""
        from prior_auth_demo.clinical_review_engine import lookup_icd10_code

        result = lookup_icd10_code("C34.11", reference_data_dir / "icd10cm_codes_2026.tsv")
        assert result is not None
        assert "upper lobe" in result["description"].lower()

    def test_lookup_finds_rheumatoid_arthritis_code(self, reference_data_dir: Path) -> None:
        """M05.79 (RA with RF, multiple sites) should be found."""
        from prior_auth_demo.clinical_review_engine import lookup_icd10_code

        result = lookup_icd10_code("M05.79", reference_data_dir / "icd10cm_codes_2026.tsv")
        assert result is not None
        assert "rheumatoid" in result["description"].lower()


@pytest.mark.unit
class TestConfidenceRouting:
    """Tests for confidence-based determination routing logic."""

    def test_confidence_routing_auto_approve(self) -> None:
        """Confidence >= 0.85 with APPROVED determination stays APPROVED."""
        from prior_auth_demo.clinical_review_engine import apply_confidence_routing

        result = apply_confidence_routing("APPROVED", 0.90, 0.85, 0.60)
        assert result == "APPROVED"

    def test_confidence_routing_high_confidence_denied_stays_denied(self) -> None:
        """DENIED determination is preserved regardless of confidence."""
        from prior_auth_demo.clinical_review_engine import apply_confidence_routing

        result = apply_confidence_routing("DENIED", 0.95, 0.85, 0.60)
        assert result == "DENIED"

    def test_confidence_routing_low_confidence_approved_becomes_pended(self) -> None:
        """Confidence 0.60-0.84 with APPROVED routes to PENDED_FOR_REVIEW."""
        from prior_auth_demo.clinical_review_engine import apply_confidence_routing

        result = apply_confidence_routing("APPROVED", 0.70, 0.85, 0.60)
        assert result == "PENDED_FOR_REVIEW"

    def test_confidence_routing_very_low_never_auto_denies(self) -> None:
        """Confidence < 0.60 with APPROVED routes to PENDED_FOR_REVIEW, never DENIED."""
        from prior_auth_demo.clinical_review_engine import apply_confidence_routing

        result = apply_confidence_routing("APPROVED", 0.40, 0.85, 0.60)
        assert result == "PENDED_FOR_REVIEW"

    def test_confidence_routing_pended_missing_info_preserved(self) -> None:
        """PENDED_MISSING_INFO is always preserved regardless of confidence."""
        from prior_auth_demo.clinical_review_engine import apply_confidence_routing

        result = apply_confidence_routing("PENDED_MISSING_INFO", 0.90, 0.85, 0.60)
        assert result == "PENDED_MISSING_INFO"

    def test_confidence_at_exact_threshold_approves(self) -> None:
        """Confidence exactly at 0.85 threshold should auto-approve."""
        from prior_auth_demo.clinical_review_engine import apply_confidence_routing

        result = apply_confidence_routing("APPROVED", 0.85, 0.85, 0.60)
        assert result == "APPROVED"


@pytest.mark.unit
class TestNpiValidation:
    """Tests for NPI format and Luhn-10 validation."""

    def test_valid_npi_passes(self) -> None:
        """Known valid NPI 1234567893 should pass validation."""
        from prior_auth_demo.clinical_review_engine import validate_npi

        result = validate_npi("1234567893")
        assert result["valid"] is True

    def test_invalid_npi_check_digit_fails(self) -> None:
        """NPI with wrong check digit should fail."""
        from prior_auth_demo.clinical_review_engine import validate_npi

        result = validate_npi("1234567890")
        assert result["valid"] is False

    def test_npi_wrong_length_fails(self) -> None:
        """NPI with wrong length should fail."""
        from prior_auth_demo.clinical_review_engine import validate_npi

        result = validate_npi("12345")
        assert result["valid"] is False

    def test_npi_non_numeric_fails(self) -> None:
        """NPI with non-numeric characters should fail."""
        from prior_auth_demo.clinical_review_engine import validate_npi

        result = validate_npi("123456789A")
        assert result["valid"] is False


@pytest.mark.unit
class TestCmsCoverageLookup:
    """Tests for CMS coverage criteria lookup from local JSON."""

    def test_lookup_returns_criteria_for_known_procedure(self) -> None:
        """Coverage criteria for CPT 72148 (lumbar MRI) should be found."""
        from prior_auth_demo.clinical_review_engine import check_cms_coverage

        result = check_cms_coverage("72148")
        assert result is not None
        assert result["procedure_code"] == "72148"
        assert len(result["coverage_requirements"]) > 0
        assert len(result["references"]) > 0

    def test_lookup_returns_none_for_unknown_procedure(self) -> None:
        """Unknown procedure code should return None."""
        from prior_auth_demo.clinical_review_engine import check_cms_coverage

        result = check_cms_coverage("99999")
        assert result is None

    def test_lookup_returns_oncology_criteria(self) -> None:
        """Coverage criteria for J9271 (Keytruda) should mention NCCN."""
        from prior_auth_demo.clinical_review_engine import check_cms_coverage

        result = check_cms_coverage("J9271")
        assert result is not None
        references_text = " ".join(result.get("references", []))
        assert "NCCN" in references_text


@pytest.mark.unit
class TestRetrieveClinicalData:
    """Tests for extracting clinical data from FHIR Bundles."""

    def test_extracts_patient_from_bundle(self, sample_cases_dir: Path) -> None:
        """Clinical data extraction finds Patient resources in Bundle."""
        import json as json_mod

        from fhir.resources.R4B.bundle import Bundle

        from prior_auth_demo.clinical_review_engine import retrieve_clinical_data

        filepath = sample_cases_dir / "01_lumbar_mri_clear_approval.json"
        with filepath.open() as f:
            data = json_mod.load(f)
        bundle = Bundle.model_validate(data)
        result = retrieve_clinical_data(bundle)
        assert len(result["patients"]) >= 1
        assert len(result["conditions"]) >= 1
        assert len(result["supporting_info"]) >= 1

    def test_extracts_claim_details(self, sample_cases_dir: Path) -> None:
        """Clinical data extraction includes Claim details."""
        import json as json_mod

        from fhir.resources.R4B.bundle import Bundle

        from prior_auth_demo.clinical_review_engine import retrieve_clinical_data

        filepath = sample_cases_dir / "01_lumbar_mri_clear_approval.json"
        with filepath.open() as f:
            data = json_mod.load(f)
        bundle = Bundle.model_validate(data)
        result = retrieve_clinical_data(bundle)
        assert result["claim_details"].get("use") == "preauthorization"


@pytest.mark.unit
class TestCliModule:
    """Tests for command_line_demo module."""

    def test_module_is_importable(self) -> None:
        """command_line_demo module can be imported without errors."""
        import prior_auth_demo.command_line_demo  # noqa: F401

    def test_format_determination_badge(self) -> None:
        """Determination badge formatting produces expected strings."""
        from prior_auth_demo.command_line_demo import format_determination_badge

        approved = format_determination_badge("APPROVED")
        assert "APPROVED" in approved

        denied = format_determination_badge("DENIED")
        assert "DENIED" in denied

        pended = format_determination_badge("PENDED_FOR_REVIEW")
        assert "PENDED_FOR_REVIEW" in pended
